import { Rubik, Roboto, Poppins } from 'next/font/google';
import type { Metadata } from 'next';

const roboto = Roboto({
	weight: ['400', '700', '900'],
	subsets: ['latin'],
});

const poppins = Poppins({
	weight: ['400', '700', '900'],
	subsets: ['latin'],
});

const rubik = Rubik({
	weight: ['400', '700', '900'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className={rubik.className}>
			<body className={rubik.className}>{children}</body>
		</html>
	);
}
