import { Rubik, Roboto, Poppins } from 'next/font/google'
// import localFont from 'next/font/local'
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'

const roboto = Roboto({
	weight: ['400', '700', '900'],
	subsets: ['latin'],
})

const poppins = Poppins({
	weight: ['400', '700', '900'],
	subsets: ['latin'],
})

const rubik = Rubik({
	weight: ['400', '700', '900'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' className={roboto.className}>
			
			<body className={rubik.className}>{children}</body>
		</html>
	)
}
